

import Frame from 'components/frame'
import { naviPage } from 'model/navi'
import frame from '@/styles/Frame.module.css';
import Head from 'next/head';


export default function Home() {
  return (
    <>
    <Head>
        <title>iBIS: v1</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
    </Head>
    <div>
      <Frame current={naviPage[0]} ></Frame>
      <div className={frame.frame}>
      </div>
    </div>
    </>
  )
}
